spring:
  datasource:
    url: jdbc:mysql://111.231.28.177:3306/ygy?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Zju123!@#

  jpa:
    database: mysql
    show-sql: true
